apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: umami-db-secret
  namespace: umami
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: umami-db-secret
    creationPolicy: Owner
  data:
    - secretKey: DATABASE_URL
      remoteRef:
        key: umami/database-url
        property: DATABASE_URL
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: umami-app-secret
  namespace: umami
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: umami-app-secret
    creationPolicy: Owner
  data:
    - secretKey: APP_SECRET
      remoteRef:
        key: umami/app-secrets
        property: APP_SECRET
    - secretKey: HASH_SALT
      remoteRef:
        key: umami/app-secrets
        property: HASH_SALT